export const ADD = "ADD";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
